### ISSUE TITLE
Missing examples 

### ISSUE THREAD

**Issue by netmindz** [vortigont/LedFB#1]
It would be easier to understand how to use this library if you provide one or two minimal examples

**Comment by vortigont** [comment]
Hi @netmindz, yeah, true... :)
Kind of using it as a part of my project, did not expect anybody else will dive into it.
Let me know which part you are more interested in and I will come up with examples one by one soon.

**Comment by netmindz** [comment]
An example of dynamic pin selection please

**Comment by vortigont** [comment]
@netmindz 
hope this will help - https://github.com/vortigont/LedFB/tree/main/examples/00_FastLED_ESP32_run-time_RMT
let me know if I missed something

**Comment by netmindz** [comment]
Perfect. Thanks
